[build]
  base = "."
  command = "npm install && cd frontend && npm install typescript vite && npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "20"

# SPA fallback - MUST be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html"
[context.production.environment]
  VITE_DEV_MODE = "false"
  VITE_SITE_URL = "https://deal-desk.netlify.app"
  VITE_MONOGOTO_OS_URL = "https://monogoto-os.netlify.app"
  VITE_SUPABASE_URL = "https://uddmjjgnexdazfedrytt.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkZG1qamduZXhkYXpmZWRyeXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjQ2OTUsImV4cCI6MjA2MzM0MDY5NX0.A_034WOQ-JJ3DDvMux5fLXayJ4pUk3_WXnVTJI-wSL0"
